CREATE TABLE IF NOT EXISTS domains (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    host VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'pending_dns',
    dns_verified_at TIMESTAMP NULL,
    ssl_ready_at TIMESTAMP NULL,
    provider_domain_id VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE domains ADD COLUMN IF NOT EXISTS host VARCHAR(255);
ALTER TABLE domains ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'pending_dns';
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dns_verified_at TIMESTAMP NULL;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS ssl_ready_at TIMESTAMP NULL;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS provider_domain_id VARCHAR(255) NULL;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE domains
SET host = LOWER(REGEXP_REPLACE(REGEXP_REPLACE(url, '^https?://', ''), '/.*$', ''))
WHERE host IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS domains_host_unique ON domains (LOWER(host));

CREATE TABLE IF NOT EXISTS regions (
    id SERIAL PRIMARY KEY,
    domain_id INTEGER REFERENCES domains(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    domain_id INTEGER REFERENCES domains(id) ON DELETE CASCADE,
    region_id INTEGER REFERENCES regions(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
